name: Build binaries
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release --locked --features cli --bin epscan
      - uses: actions/upload-artifact@v4
        with:
          name: epscan-${{ matrix.os }}
          path: |
            target/release/epscan
            target/release/epscan.exe
